site_name: NGS - Quality control, Alignment, Visualisation
nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Day 1:
      - Introduction: day1/intro.md
      - Sequencing technologies: day1/sequencing_technologies.md
      - Setup: day1/server_login.md
      - Reproducibility: day1/reproducibility.md
      - Quality control: day1/quality_control.md
    - Day 2:
      - Read alignment: day2/read_alignment.md
      - File types: day2/file_types.md
      - Samtools: day2/samtools.md
    - Day 3:
      - IGV and visualisation: day3/igv_visualisation.md
    - Group work: group_work.md

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg
  custom_dir: overrides

# Repository
repo_name: sib-swiss/NGS-introduction-training
repo_url: https://github.com/sib-swiss/NGS-introduction-training
edit_uri: edit/main/docs/

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
